import java.awt.Window;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class PublishDialog {
   JFrame frame = new JFrame("PublishDialog");

   /**
    * Creates new form Publish
    */
   public void show() {
      frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      initComponents();
      frame.pack();
      frame.setVisible(true);
      frame.getContentPane().setVisible(true);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();

      jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
      jLabel1.setText("Are you sure you want to publish Winter_2014_2?");

      jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
      jLabel2.setText("Publish Schedule to Web");

      jButton1.setText("Cancel");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      jButton2.setText("Publish");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(frame.getContentPane());
      frame.getContentPane().setLayout(layout);
      layout.setHorizontalGroup(layout
         .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(
            layout
               .createSequentialGroup()
               .addGroup(
                  layout
                     .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(
                        layout.createSequentialGroup().addGap(56, 56, 56).addComponent(jLabel2))
                     .addGroup(
                        layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addGroup(
            javax.swing.GroupLayout.Alignment.TRAILING,
            layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(jButton2)
               .addGap(47, 47, 47).addComponent(jButton1).addGap(93, 93, 93)));
      layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(
            layout
               .createSequentialGroup()
               .addGap(34, 34, 34)
               .addComponent(jLabel2)
               .addGap(37, 37, 37)
               .addComponent(jLabel1)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38,
                  Short.MAX_VALUE)
               .addGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jButton1).addComponent(jButton2)).addGap(39, 39, 39)));
   }// </editor-fold>

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
      JButton button = (JButton) evt.getSource();
      Window buttonFrame = SwingUtilities.windowForComponent(button);

      buttonFrame.dispose();
   }

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
      JButton button = (JButton) evt.getSource();
      Window buttonFrame = SwingUtilities.windowForComponent(button);
      
      buttonFrame.dispose();

   }

   // Variables declaration - do not modify
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   // End of variables declaration
}
