import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;

import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicBorders.RadioButtonBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

public class AdminInstructorPrefs extends javax.swing.JPanel {
   
// Variables declaration - do not modify                     
   private javax.swing.JPanel JGridCoursePrefs;
   private javax.swing.JCheckBox jCheckBoxLockPrefs;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JList jListInstructors;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanelCoursePreferences;
   private javax.swing.JPanel jPanelInstructorList;
   private javax.swing.JPanel jPanelLockPrefs;
   private javax.swing.JPanel jPanelTimePrefs;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JTable jTableTimePrefs;
   
   private AdminMainView parent;
   // End of variables declaration 

    /**
     * Creates new form AdminInstructorPrefs
     */
    public AdminInstructorPrefs(AdminMainView parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanelInstructorList = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListInstructors = new javax.swing.JList();
        jPanelTimePrefs = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTimePrefs = new javax.swing.JTable();
        jPanelCoursePreferences = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        JGridCoursePrefs = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelLockPrefs = new javax.swing.JPanel();
        jCheckBoxLockPrefs = new javax.swing.JCheckBox();

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Instructor Preferences");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Instructor");

        jListInstructors.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {
               "Paul Hatalsky",
               "Clint Staley",
               "John Seng",
               "Phillip Nico",
               "Julie Workman",
               "Timothy Kearns",
               "Hasmik Gharibyan",
               "John Dalby",
               "Kurt Mammen",
               "Ignatios Vakalis",
               "John Clements",
               "David Janzen",
               "Clark Turner",
               "Gene Fisher",
               "William Buckalew",
               "Christopher Lupo",
               "Alexander Dekhtyar",
               "Foaad Khosmood" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListInstructors);

        javax.swing.GroupLayout jPanelInstructorListLayout = new javax.swing.GroupLayout(jPanelInstructorList);
        jPanelInstructorList.setLayout(jPanelInstructorListLayout);
        jPanelInstructorListLayout.setHorizontalGroup(
            jPanelInstructorListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInstructorListLayout.createSequentialGroup()
                .addGroup(jPanelInstructorListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInstructorListLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3))
                    .addGroup(jPanelInstructorListLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanelInstructorListLayout.setVerticalGroup(
            jPanelInstructorListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInstructorListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Time Preferences");

        Cell[][] timeTable = new Cell[16][];  
        Color c = Color.green;
        
        for (int time = 7; time <= 22; time++) {
           String t = time < 12 ? time + ":00AM" : time == 12 ? "12:00PM" : (time - 12) + ":00PM";
           timeTable[time - 7] = new Cell[]{new Cell(t,c), new Cell(c), new Cell(c), new Cell(c),new Cell(c),new Cell(c),new Cell(c)};
        }
        
        DefaultTableModel model = new DefaultTableModel(16, 7) ;
        model.setDataVector(timeTable, new String[] { "Time", "Mon.", "Tues.", "Wed.", "Thurs.", "Fri.", "Sat." });
        
        jTableTimePrefs.setModel(model);
        
        jTableTimePrefs.setDefaultRenderer(Object.class, new TableCellRenderer(){
           private DefaultTableCellRenderer DEFAULT_RENDERER =  new DefaultTableCellRenderer();
           
           @Override
           public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
              Component c = DEFAULT_RENDERER.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
              Cell cell = (Cell)value;
              
              
              if (hasFocus && cell.isColorable() && !cell.backgroundIsSet()) {
                 c.setBackground(Color.GREEN);
                 cell.backgroundColor = Color.GREEN;
              }
              else if (hasFocus && cell.backgroundIsSet()) {
                 Color color = row % 2 == 0 ? Color.WHITE : Color.LIGHT_GRAY;
                 c.setBackground(color);
                 cell.backgroundColor = color;
              }
              else if (cell.backgroundIsSet())
                 c.setBackground(cell.backgroundColor);
              else {
                 c.setBackground(row % 2 == 0 ? Color.WHITE : Color.LIGHT_GRAY);
              }
              return c;
           }
        });
        
        
        
        jScrollPane2.setViewportView(jTableTimePrefs);

        javax.swing.GroupLayout jPanelTimePrefsLayout = new javax.swing.GroupLayout(jPanelTimePrefs);
        jPanelTimePrefs.setLayout(jPanelTimePrefsLayout);
        jPanelTimePrefsLayout.setHorizontalGroup(
            jPanelTimePrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimePrefsLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTimePrefsLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTimePrefsLayout.setVerticalGroup(
            jPanelTimePrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimePrefsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Course Preferences");

        JGridCoursePrefs.setLayout(new java.awt.GridLayout(11, 4));

        String[] prefixes = new String[] {"CPE","CPE","CPE","CSC","CSC","CPE",
                                         "CPE","CPE","CPE","CPE","CPE"};
        String[] courseNums = new String[] {"101","102","103","141","225","315",
           "349","307","308","309","453"};
        
        int borderWidth = 1;
        
        JLabel prefixTitle = new JLabel("Prefix");
        prefixTitle.setBorder(BorderFactory.createMatteBorder(borderWidth, borderWidth, borderWidth, borderWidth, Color.BLACK));
        prefixTitle.setHorizontalAlignment(SwingConstants.CENTER);
        JGridCoursePrefs.add(prefixTitle);
        
        JLabel courseTitle = new JLabel("Course No.");
        courseTitle.setBorder(BorderFactory.createMatteBorder(borderWidth, 0, borderWidth, borderWidth, Color.BLACK));
        courseTitle.setHorizontalAlignment(SwingConstants.CENTER);
        JGridCoursePrefs.add(courseTitle);
        
        JLabel qualifiedTitle = new JLabel("Not qualified");
        qualifiedTitle.setBorder(BorderFactory.createMatteBorder(borderWidth, 0, borderWidth, borderWidth, Color.BLACK));
        qualifiedTitle.setHorizontalAlignment(SwingConstants.CENTER);
        JGridCoursePrefs.add(qualifiedTitle);

        JLabel preferTitle = new JLabel("Don't prefer - prefer");
        preferTitle.setBorder(BorderFactory.createMatteBorder(borderWidth, 0, borderWidth, borderWidth, Color.BLACK));
        preferTitle.setHorizontalAlignment(SwingConstants.CENTER);
        JGridCoursePrefs.add(preferTitle);
        
        
        //JGridCoursePrefs.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
        
        
           
        for (int i = 0; i < 10; i++) {
           JLabel prefix = new JLabel(prefixes[i]);
           prefix.setBorder(BorderFactory.createMatteBorder(0, borderWidth, borderWidth, borderWidth, Color.BLACK));
           JGridCoursePrefs.add(prefix);
           
           JLabel courseNum = new JLabel(courseNums[i]);
           courseNum.setBorder(BorderFactory.createMatteBorder(0, 0, borderWidth, borderWidth, Color.BLACK));
           JGridCoursePrefs.add(courseNum);
           
           JPanel notQual =new JPanel();
           JRadioButton notQualBtn = new JRadioButton();
           notQual.add(notQualBtn);
           notQual.setBorder(BorderFactory.createMatteBorder(0, 0, borderWidth, borderWidth, Color.BLACK));
           JGridCoursePrefs.add(notQual);
           
           JPanel prefs =new JPanel();
           prefs.add(new JRadioButton());
           prefs.add(new JRadioButton());
           prefs.add(new JRadioButton());
           prefs.add(new JRadioButton());
           prefs.add(new JRadioButton());

           prefs.setBorder(BorderFactory.createMatteBorder(0, 0, borderWidth, borderWidth, Color.BLACK));
           JGridCoursePrefs.add(prefs);
        }

        GroupLayout jPanelCoursePreferencesLayout = new javax.swing.GroupLayout(jPanelCoursePreferences);
        jPanelCoursePreferences.setLayout(jPanelCoursePreferencesLayout);
        jPanelCoursePreferencesLayout.setHorizontalGroup(
            jPanelCoursePreferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCoursePreferencesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanelCoursePreferencesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JGridCoursePrefs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCoursePreferencesLayout.setVerticalGroup(
            jPanelCoursePreferencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCoursePreferencesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JGridCoursePrefs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setText("Instructor Preferences");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(246, 246, 246))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jCheckBoxLockPrefs.setText("Lock instructor preferences");

        javax.swing.GroupLayout jPanelLockPrefsLayout = new javax.swing.GroupLayout(jPanelLockPrefs);
        jPanelLockPrefs.setLayout(jPanelLockPrefsLayout);
        jPanelLockPrefsLayout.setHorizontalGroup(
            jPanelLockPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLockPrefsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxLockPrefs)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanelLockPrefsLayout.setVerticalGroup(
            jPanelLockPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLockPrefsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxLockPrefs)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelInstructorList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTimePrefs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCoursePreferences, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLockPrefs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTimePrefs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInstructorList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelCoursePreferences, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelLockPrefs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }                                       
}

